### ISSUE TITLE
Cannot read properties

### ISSUE THREAD

**Issue by JoChenSchae** [jalibu/MMM-BoschSmartHome#11]
### Platform

Raspberry

### MagicMirror Version

2.24.0

### Module Version

1.4.1

### Description

Starting the module it will displays an error "Cannot read properties of undefined (reading 'sort')"

Die Message showed up after an update of the BOSCH BRIDGE.

### Steps to reproduce

1. Start MM
2.  Wait until the modules load

### config.js

```javascript
config file is the same as in descirption
```

**Comment by jalibu** [comment]
Hi @JoChenSchae ,

fixed in the new released version 1.4.2

After pulling the changes, you need to execute a `npm i` in the module's folder
