### ISSUE TITLE
Door-/ Window Contacts

### ISSUE THREAD

**Issue by boehmch65** [jalibu/MMM-BoschSmartHome#12]
Hello

first of all thank you for the great module, am very satisfied with it. In the description it says that window contacts can also be displayed. However, I find nothing in the config files. Now my question is that, or how would that look. 

Thanks for feedback Christian

**Comment by jalibu** [comment]
Hi @boehmch65,

sorry for this delayed answer:

<img width="310" alt="image" src="https://github.com/jalibu/MMM-BoschSmartHome/assets/25933231/ae026b56-0881-45e9-9246-279cbe929b3e">

Open windows are displayed with a "wind" symbol on a room (see Bad for example).
