### ISSUE TITLE
Warning: web-loaders.js:87 [Deprecation] Synchronous XMLHttpRequest on the main thread

### ISSUE THREAD

**Issue by MajorC1983** [jalibu/MMM-BoschSmartHome#5]
I am not sure, what the module wants me to tell:

`web-loaders.js:87 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

**Comment by jalibu** [comment]
Please check out the latest version

**Comment by MajorC1983** [comment]
Perfect, the message is gone. Thank you!
