### ISSUE TITLE
Sorting of the shown rooms

### ISSUE THREAD

**Issue by MajorC1983** [jalibu/MMM-BoschSmartHome#7]
**Describe the solution you'd like**
An option to sort the shown rooms would be nice. I would like to change the order of the rooms.

**Comment by jalibu** [comment]
@MajorC1983  Hast ne Idee oder nen Vorschlag wie man das in der Config abbilden könnte?

**Comment by MajorC1983** [comment]
Maybe:

`config: {
   roomOrder:  ["Bed Room", "Kitchen", "Dungeon"], //Sorts the rooms from top to bottom
  }`

**Comment by jalibu** [comment]
@MajorC1983 da die Umsetzung ein "No-Brainer" war, hab ichs kurz eingetüdelt. Teste ma bidde

**Comment by MajorC1983** [comment]
Funktioniert! Thank you.
